# THIS IS HEADING 1 (H1 TAG)
## HEADING2(H2 TAG)
### H3
#### H4
##### H5
###### H6


# ESC+M-->CONVERT TO MARKDOWN CELL
# ESC+Y-->CONVERT MARKDOWN TO CODING CELL
# SHIFT+ENTER-->FOR EXECUTING CURRENT CELL 
# ESC+A-->INSERT CELL ABOVE THE CURRENT CELL
# ESC+B-->INSERT CELL BELOW THE CURRENT CELL

# NUMPY
- NUMERICAL PYTHON
- MULTIDIMENTIONAL
- IT TAKES LESS TIME TO EXECUTE
- NUMERICAL OPERATIONS

In [1]:
import numpy as np

In [2]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [3]:
d1=np.array([45,74,85,36,65,57])
d1

array([45, 74, 85, 36, 65, 57])

In [4]:
d1.shape

(6,)

In [5]:
d1.size

6

In [6]:
d1.ndim

1

In [7]:
d1

array([45, 74, 85, 36, 65, 57])

In [8]:
d1[1]

74

In [9]:
d1[2]

85

In [10]:
d1[0:3]

array([45, 74, 85])

In [11]:
d1[3:0:-1]

array([36, 85, 74])

In [12]:
data = np.array(['chinna','chintu',123,99.8])
data

array(['chinna', 'chintu', '123', '99.8'], dtype='<U6')

In [13]:
import time 
start_time = time.time()
list1=[x for x in range(1,100000)]
list2=[y for y in range(1,100000)] 
op = list(map(lambda x,y : x*y,list1,list2))
end_time= time.time()
print("Time taken by list concept",end_time-start_time)

Time taken by list concept 0.04685854911804199


In [15]:
import time 
start_time1=time.time()
ar1=np.array(list1)
ar2=np.array(list2)
ar1*ar2
end_time1=time.time()
print("time taken by numpy is",end_time1-start_time1)

time taken by numpy is 0.015607833862304688


In [16]:
# 2-D array declaration 
d2=np.array([[45,74,36],[96,87,69],[14,25,63]])
d2

array([[45, 74, 36],
       [96, 87, 69],
       [14, 25, 63]])

In [17]:
d2.ndim

2

In [20]:
d2.shape

(3, 3)

In [19]:
d2.size

9

In [21]:
d2[0]

array([45, 74, 36])

In [22]:
d2[0,2]

36

In [24]:
max(d2[0])

74

In [25]:
max(d2[1])

96

In [26]:
d2[1].max()

96

In [27]:
# maximum marks of third subject for 3 students
max(d2[:,2])

69

In [28]:
# min marks of first subject of 3 students
min(d2[:,0])

14

In [29]:
sum(d2)

array([155, 186, 168])

In [30]:
d2.sum()

509

In [31]:
d2.sum(axis=0)

array([155, 186, 168])

In [32]:
d2.sum(axis=1)

array([155, 252, 102])

In [33]:
d3=np.array([[[1,2,3],[4,5,6]],
             [[7,8,9],[10,11,12]]])
d3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [34]:
d3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
d3[0,0]

array([1, 2, 3])

In [36]:
d3[0,0]

array([1, 2, 3])

In [38]:
d3[0,0,1]

2

## arange()

In [39]:
range(1,10)

range(1, 10)

In [40]:
for i in range(1,11):
    print(i,end=" ")

1 2 3 4 5 6 7 8 9 10 

In [42]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
for i in range(1,10,0.5):
    print(i)

TypeError: 'float' object cannot be interpreted as an integer

In [45]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [46]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

# zeos matrix

In [48]:
np.zeros([10,20])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [49]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
d21=np.array([[[14,25,36,41,52],[24,51,35,15,16]]])

In [56]:
add_marks=np.tile(5,[2,5])
add_marks

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [57]:
final_marks=d21+add_marks
final_marks

array([[[19, 30, 41, 46, 57],
        [29, 56, 40, 20, 21]]])

In [59]:
mat=np.array([[1,10,20],[2,20,30],[3,45,55]])
mat

array([[ 1, 10, 20],
       [ 2, 20, 30],
       [ 3, 45, 55]])

In [60]:
np.linalg.inv(mat)

array([[-1.66666667,  2.33333333, -0.66666667],
       [-0.13333333, -0.03333333,  0.06666667],
       [ 0.2       , -0.1       ,  0.        ]])

In [61]:
np.linalg.eig(mat)

(array([79.2418833 , -0.76390403, -2.47797927]),
 array([[-0.27476378, -0.98372828, -0.86503683],
        [-0.44175308, -0.11022856, -0.37213216],
        [-0.85402523,  0.14187439,  0.33649509]]))

# random

In [62]:
np.random.random(10)

array([0.70526638, 0.81044424, 0.25368691, 0.18668209, 0.47789167,
       0.73020932, 0.08406172, 0.18538722, 0.13641711, 0.56623966])

In [64]:
np.random.random(100)

array([0.2597399 , 0.40247976, 0.18372272, 0.92918871, 0.07808315,
       0.8829236 , 0.1478174 , 0.27435842, 0.65986812, 0.46782865,
       0.36841476, 0.81020799, 0.49916444, 0.83931114, 0.55448918,
       0.19204564, 0.05674029, 0.89098635, 0.74098055, 0.55444425,
       0.67138624, 0.7117886 , 0.81905945, 0.28567058, 0.88989995,
       0.86844933, 0.90949375, 0.75428559, 0.25841166, 0.03268558,
       0.97411441, 0.10840302, 0.62173027, 0.9903471 , 0.81320833,
       0.75104689, 0.69944197, 0.06737557, 0.11371793, 0.28008142,
       0.22406014, 0.40004528, 0.37720413, 0.76185563, 0.78486648,
       0.39514203, 0.15442536, 0.76847666, 0.05146732, 0.16318627,
       0.74748254, 0.9605758 , 0.26819944, 0.48059593, 0.80541569,
       0.517253  , 0.25251333, 0.53434248, 0.04259678, 0.37321909,
       0.42629064, 0.3897683 , 0.78859242, 0.39289492, 0.53112022,
       0.6120376 , 0.87797549, 0.05769202, 0.54492091, 0.47411872,
       0.20344257, 0.118147  , 0.92793781, 0.3065417 , 0.70321

In [65]:
np.random.randint(10)

5

In [66]:
np.random.randint(10)

6

In [67]:
np.random.rand(10)

array([0.86929007, 0.13078227, 0.6231021 , 0.89551109, 0.96248292,
       0.32061774, 0.60769538, 0.94115503, 0.66989094, 0.18071284])

In [68]:
np.random.randint(10,25,[4,6])

array([[22, 23, 19, 12, 20, 20],
       [12, 20, 13, 14, 16, 20],
       [18, 23, 13, 16, 23, 15],
       [18, 10, 18, 12, 13, 10]])

In [69]:
np.random.randint(1,13,[4,3])

array([[11,  3,  8],
       [11,  9,  5],
       [ 1, 11,  7],
       [ 7, 12,  9]])

In [70]:
np.random.randint(10,20,30)

array([18, 13, 16, 13, 15, 17, 11, 11, 18, 12, 11, 18, 10, 13, 17, 17, 19,
       11, 10, 12, 16, 19, 10, 19, 14, 15, 12, 18, 13, 13])

In [71]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [72]:
np.arange(1,49).reshape(4,3,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]],

       [[37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]]])

In [73]:
np.sin(90)

0.8939966636005579

In [74]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [75]:
np.sinh(10)

11013.232874703393

In [76]:
np.arcsin(1)

1.5707963267948966

In [77]:
np.arcsin(90)

<ipython-input-77-83f060775ee7>:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(90)


nan

In [78]:
array=np.arange(1,10).reshape(3,3)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
array.max()

9

In [80]:
array.min()

1

In [81]:
# for finding max value index 
array.argmax()

8

In [82]:
array.argmin()

0

In [84]:
sec1=np.array(np.random.randint(10,20,[4,4]))
sec1

array([[11, 15, 16, 15],
       [16, 15, 13, 14],
       [14, 10, 10, 16],
       [14, 12, 12, 16]])

In [85]:
sec2=np.array(np.random.randint(1,10,[4,4]))
sec2

array([[3, 3, 6, 9],
       [4, 5, 7, 4],
       [5, 7, 2, 8],
       [6, 6, 8, 6]])

In [92]:
sec2=np.array(np.random.randint(1,10,[4,4]))
sec2

array([[4, 7, 6, 3],
       [1, 9, 4, 3],
       [5, 6, 1, 9],
       [2, 9, 1, 8]])

In [93]:
np.vstack((sec1,sec2))

array([[11, 15, 16, 15],
       [16, 15, 13, 14],
       [14, 10, 10, 16],
       [14, 12, 12, 16],
       [ 4,  7,  6,  3],
       [ 1,  9,  4,  3],
       [ 5,  6,  1,  9],
       [ 2,  9,  1,  8]])

In [94]:
np.hstack((sec1,sec2))

array([[11, 15, 16, 15,  4,  7,  6,  3],
       [16, 15, 13, 14,  1,  9,  4,  3],
       [14, 10, 10, 16,  5,  6,  1,  9],
       [14, 12, 12, 16,  2,  9,  1,  8]])

In [95]:
np.column_stack((sec1,sec2))

array([[11, 15, 16, 15,  4,  7,  6,  3],
       [16, 15, 13, 14,  1,  9,  4,  3],
       [14, 10, 10, 16,  5,  6,  1,  9],
       [14, 12, 12, 16,  2,  9,  1,  8]])

In [96]:
sec1+sec2

array([[15, 22, 22, 18],
       [17, 24, 17, 17],
       [19, 16, 11, 25],
       [16, 21, 13, 24]])

In [97]:
sec1*sec2

array([[ 44, 105,  96,  45],
       [ 16, 135,  52,  42],
       [ 70,  60,  10, 144],
       [ 28, 108,  12, 128]])

In [98]:
sec1@sec2

array([[169, 443, 157, 342],
       [172, 451, 183, 322],
       [148, 392, 150, 290],
       [160, 422, 160, 314]])

In [99]:
sec1.dot(sec2)

array([[169, 443, 157, 342],
       [172, 451, 183, 322],
       [148, 392, 150, 290],
       [160, 422, 160, 314]])

In [100]:
sec1.transpose()

array([[11, 16, 14, 14],
       [15, 15, 10, 12],
       [16, 13, 10, 12],
       [15, 14, 16, 16]])

In [101]:
sec1.trace()

52

In [102]:
np.hsplit(sec1,2)

[array([[11, 15],
        [16, 15],
        [14, 10],
        [14, 12]]),
 array([[16, 15],
        [13, 14],
        [10, 16],
        [12, 16]])]

In [103]:
np.hsplit(sec1,[2,2])

[array([[11, 15],
        [16, 15],
        [14, 10],
        [14, 12]]),
 array([], shape=(4, 0), dtype=int32),
 array([[16, 15],
        [13, 14],
        [10, 16],
        [12, 16]])]

In [105]:
np.vsplit(sec1,[2,3])

[array([[11, 15, 16, 15],
        [16, 15, 13, 14]]),
 array([[14, 10, 10, 16]]),
 array([[14, 12, 12, 16]])]

In [106]:
np.abs(100.25)

100.25

In [107]:
np.abs(-100.25)

100.25

In [108]:
np.all(sec1>0)

True

In [109]:
np.any(sec1<0)

False

In [110]:
np.round(12.36)

12.0

In [111]:
np.round(12.63)

13.0

In [112]:
np.floor(10.23)

10.0

In [113]:
np.ceil(10.23)

11.0

In [114]:
np.floor(10.96)

10.0

In [115]:
np.ceil(10.93)

11.0